### ISSUE TITLE
Preview is not working for me

### ISSUE THREAD

**Issue by lucax88x** [gfanto/fzf-lsp.nvim#1]
Screenshot attached.

![Screenshot_2020-12-07_12-19-35](https://user-images.githubusercontent.com/6294464/101344878-80a4f700-3886-11eb-82a1-047bf1857e3b.png)

**Comment by gfanto** [comment]
I'm sorry about that, and thanks for giving me the screenshot, unfortunately i cannot see the error, but judging by the line number and the "B" at the start of the error it looks like it cannot find the `bat` command in your PATH.
Can you check if you have bat installed and available with your PATH?

**Comment by lucax88x** [comment]
Yeah right, I did not install this one.

Thanks,
Luca

**Comment by lucax88x** [comment]
Can I suggest to give a better explanation on the preview, or even fallback to normal cat?

**Comment by gfanto** [comment]
Yes, my initial tought was to "force" people to install bat, because it is very hard to understand what you're looking for when it's all white, especially because the center line is not highlighted, but now i think i'll follow your suggestion falling back to cat. Thanks!
