### ISSUE TITLE
Workspace Diagnostics

### ISSUE THREAD

**Issue by theduke** [gfanto/fzf-lsp.nvim#11]
Currently only buffer specific diagnostics are provided.

Would be awesome to have a `:WorkspaceDiagnostics` as well.

**Comment by gfanto** [comment]
Hi, unfortunately, for what i know at the moment i am writing this message, the lsp doesn't provide this functionality, but i can easily add the possibility to have the diagnostic for all the opened buffers, if you are interested in.

**Comment by EdwarKenedy** [comment]
HI, i would like to see implemented this functionality, this would be useful when working on several files

**Comment by gfanto** [comment]
Hi, sorry for the late response. As requested i've implemented it, if you run `:PlugUpdate` and restart vim you should find a new command: `:DiagnosticAll` that give you the diagnostic for all the opened buffers. Let me know if you have find problem!
