### ISSUE TITLE
other lsp clients

### ISSUE THREAD

**Issue by spamwax** [gfanto/fzf-lsp.nvim#13]
Is it possible to make this work with other LSP clients such `coc.nvim`?

**Comment by gfanto** [comment]
No, I'm sorry but I don't think it's possible.
I'm not an expert on coc, but the functions I use to query the language server are functions exported from the native neovim lsp. and it should be adapted to use other implementations of lsp, which given the size of the whole plugin it would be easier to do it from scratch.
