### ISSUE TITLE
server does not support goto_definition

### ISSUE THREAD

**Issue by wanghuibin0** [gfanto/fzf-lsp.nvim#26]
Calling :Definitions results in an error message: server does not support goto_definition. 
Besides installing this plugin, what configuration should I write additionally? Would anyone help me?

**Comment by gfanto** [comment]
Sorry, a recent breaking change in neovim caused some problems, now if you update (`:PlugUpdate` if you are using vim-plug), it should work.

For the configuration question, there is no need of any configuration, but i suggest you using this configuration line: `require"fzf_lsp".setup()` to install the async handlers that will be used as default neovim handlers for example calling `vim.lsp.buf.definition()`

**Comment by wanghuibin0** [comment]
It works, thankful to you for your help!
