### ISSUE TITLE
gopls: call_hierarchy support

### ISSUE THREAD

**Issue by rfwatson** [gfanto/fzf-lsp.nvim#27]
Hello,
When using fzf-lsp with gopls, both `IncomingCalls` and `OutgoingCalls` return an error:

```
LSP: no client attached
```

From stepping through the source, it seems that [these lines](https://github.com/gfanto/fzf-lsp.nvim/blob/0694c278f081958e48f3a6e136c130d15cf8576e/lua/fzf_lsp.lua#L87-L91) result in `supported_client` remaining false.

This is despite both of these calls working fine when called directly from nvim-lsp, and gopls (to the best of my understanding) [supporting](https://github.com/golang/tools/commit/b793a1359eac7d446e5c21c6c5ce58496109fb50) the call_hierarchy feature.

Is there a reason this shouldn't work?

**Comment by gfanto** [comment]
Hi, that was my mistake over the last update, i already fixed it, should work now.

**Comment by gfanto** [comment]
Just do `:PlugUpdate` to update the plugin

**Comment by gfanto** [comment]
I just saw now that the sync handlers, for call hierarchy functions (`: IncomingCalls`,`: OutgoingCalls`) after a neovim update don't work now, I'll fix it asap.
Asynchronous handlers are working fine.
