### ISSUE TITLE
"References" command doesn't show file names

### ISSUE THREAD

**Issue by mortymacs** [gfanto/fzf-lsp.nvim#36]
Hi,

When I want to see the list of references, it shows all the required information except file name.
Sometimes the references are in a test file while I'm looking for the main logic. In this situation, I really can't find which one is the test and which one is the actual logic.
![image](https://github.com/gfanto/fzf-lsp.nvim/assets/1261448/a7cde106-b1e2-4559-b289-10ca13e62488)

Do you have any solution for this case?

Cheers,
Mort

**Comment by gfanto** [comment]
Hi, you can set the variable `g:fzf_lsp_pretty` to false.
You can try it with
```vim
let  g:fzf_lsp_pretty = v:false
```
it should fix your problem

**Comment by mortymacs** [comment]
Thanks!
