### ISSUE TITLE
main branch is called 'main' (not 'master') which breaks vim-plug

### ISSUE THREAD

**Issue by jdrouhard** [gfanto/fzf-lsp.nvim#6]
The main branch is called "main" currently which is incompatible with vim-plug.

vim-plug expects the main branch to be called "master", otherwise you get:

```
x fzf-lsp.nvim:
     fatal: invalid reference: master
```

**Comment by gfanto** [comment]
Sorry, but i don't understand why it brakes, i use vim plug and i have installed it without problems.
If i have to give you a fast solution it would be just a replace from `Plug 'gfanto/fzf-lsp.nvim'` with `Plug 'gfanto/fzf-lsp.nvim', { 'branch': 'main' }`

**Comment by jdrouhard** [comment]
Seems like I was using an outdated version of vim-plug. Works fine now, thanks!
