### ISSUE TITLE
Error when calling References or Diagnostics command

### ISSUE THREAD

**Issue by ner0-m** [gfanto/fzf-lsp.nvim#8]
Hi,

Running the commands `:References` or `:Diagnostics` produces the following error:

> path/to/bundle/fzf-lsp.nvim/lua/fzf_lsp.lua:260: attempt to concatenate a nil value

Calling e.g `lua vim.lsp.buf.references()` yields in a result.

If you need any more info, let me know, would be great if this can be fixed.

**Comment by gfanto** [comment]
Uhm sorry about that i probably made some naive assumption in the preview configuration code, can you please give me the value of your `fzf_lsp_preview_window` variable? To do that you can just type: `:echo g:fzf_lsp_preview_window`.

**Comment by ner0-m** [comment]
It says `right:60%`

**Comment by gfanto** [comment]
Ohh ok i've probably assumed that the string version of that settings was deprecated, but it's probably still supported in fzf.vim for backward compatibility.
So i think that the fastest solution is to change your settings from something like `let g:fzf_lsp_preview_window = 'right:60%'` to `let g:fzf_lsp_preview_window = ['right:60%']`, or if you want the toggle command something like `let g:fzf_lsp_preview_window = ['right:60%', 'ctrl-/']`.
If you don't want to change that settings, as soon i have 5 minutes of free time today, i will keep the compatibilty with the string version of the setting.

**Comment by ner0-m** [comment]
That fixed it, perfect thanks! I changed it, for me a hint in the readme would be perfectly fine.
