### ISSUE TITLE
Plug command fails

### ISSUE THREAD

**Issue by j16r** [gfanto/fzf-lsp.nvim#9]
In the readme the directions are

    Plug 'gfanto/fzf-lsp.nvim'

But this fails, e.g: 

![Screen Shot 2021-03-04 at 4 13 54 PM](https://user-images.githubusercontent.com/344071/110043428-9f3f5080-7d04-11eb-877b-acf3e046b774.png)

It looks like vim-plug assumes without a branch to use `master` but this repo uses `main` ?

**Comment by j16r** [comment]
For now you can use below as a workaround:

    Plug 'gfanto/fzf-lsp.nvim', { 'branch': 'main' }

**Comment by gfanto** [comment]
Please try upgrading vim plug (`:PlugUpgrade`) this should solve the issue

**Comment by j16r** [comment]
Thanks @gfanto it did!
